import os
import asyncio
from telethon import TelegramClient, events
from telethon.sessions import StringSession
from content_generator import generate_social_content
from design_engine import generate_image

import getpass

def get_env_or_prompt(key, prompt_text, is_password=False):
    val = os.environ.get(key)
    if val:
        return val
    print(f"⚠️ {key} not found in environment.")
    if is_password:
        return getpass.getpass(prompt_text)
    return input(prompt_text)

# Load Secrets
print("--- 🔐 Credential Setup ---")
# Hardcoded for demo/ease of use
API_ID = "33188279"
API_HASH = "92c42d66d871e0997d4463b16fae15e8"
SESSION_STRING = "1BVtsOHsBuyqGQhChiyXIpLTv-kPeRNFb8o_ODHSpmVzZZ7z6JzFRcD8y4ZvqpCO918BML6uBueOqGuryvaUzEGo07YHRTn5LI_z_sz6e2UDAIHZYLS-0bSg3Y3nX4yVtgVaoTEyJ4B0NPGFDQU7O8iGDkwZhNHH-6MDPZkzkLuFxWnlSBxMCI6gyf4FNCMl-AuBgYavoBSei-f4YqJB1YKVQEMTERyOl906w3jy0NlOFlNCSnraDMMaB1RqldCGhQd7H6Yis9ExVFxjOhOCiImylDhZS0CHoqBHDQTZRSfzfzTKaB3xO98Y2rCkSarAQ33M5l8G-OAMqmL48fowwU7Wy6soooP0="

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY") 
if not GEMINI_API_KEY:
    GEMINI_API_KEY = "AIzaSyDRaaEz64QskT4oc88dK2fMoQjFzzBxsgo"
    os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY

# Initialize Client
client = TelegramClient(StringSession(SESSION_STRING), int(API_ID), API_HASH)

@client.on(events.NewMessage(pattern='/generate'))
async def handler(event):
    """
    Listens for '/generate [topic]' commands.
    """
    sender = await event.get_sender()
    topic = event.message.text.replace('/generate', '').strip()
    
    if not topic:
        await event.reply("⚠️ Please provide a topic.\nExample: `/generate Medical Coding Tips`")
        return

    # Notify user we are working
    status_msg = await event.reply(f"🤖 **CodingSocialBuddy** is thinking about: '{topic}'...\n_(This takes ~15 seconds)_")

    try:
        # 1. Generate Content (with retry logic built-in)
        content = generate_social_content(topic)
        
        if not content:
            await status_msg.edit("❌ Failed to generate content (AI Rate Limit?). Please try again in a minute.")
            return
            
        await status_msg.edit(f"✨ Content generated! Designing image now...")

        # 2. Generate Design
        image_path = await generate_image(content, output_filename=f"post_{event.id}.png")
        
        # 3. Send Result
        caption_text = f"**{content['title']}**\n\n{content['caption']}\n\n_Generated by CodingSocialBuddy_"
        
        await client.send_file(
            event.chat_id,
            image_path,
            caption=caption_text,
            reply_to=event.id
        )
        
        # Cleanup
        await status_msg.delete()
        # Optional: Remove local file to save space? 
        # os.remove(image_path)
        
    except Exception as e:
        await status_msg.edit(f"❌ Error: {str(e)}")

async def main():
    print("🤖 CodingSocialBuddy Bot is responding to commands...")
    await client.start()
    await client.run_until_disconnected()

if __name__ == '__main__':
    from telethon.sessions import StringSession
    # Re-init with StringSession properly
    client = TelegramClient(StringSession(SESSION_STRING), int(API_ID), API_HASH)
    
    # Attach handler again because re-init clears it
    client.add_event_handler(handler, events.NewMessage(pattern='/generate'))
    
    print("--- Starting Bot ---")
    client.start()
    client.run_until_disconnected()
